name: Release package

on:
 release:
  types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/
          node-version: '18'

      # Install dependencies (required by Run tests step)
      - name: Install dependencies
        run: yarn install

      # Build package
      - name: Build package
        run: yarn build

      # Publish version to public repository
      - name: Publish
        run: |
          npm ci
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
